# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0002_initial"),
    ]

    operations = [
        # --- ComponentLibrary: update category choices and max_length ---
        migrations.AlterField(
            model_name="componentlibrary",
            name="category",
            field=models.CharField(
                choices=[
                    ("process", "Process"),
                    ("datastore", "Data Store"),
                    ("external_human_actor", "External Human Actor"),
                    ("external_system_actor", "External System Actor"),
                ],
                max_length=30,
            ),
        ),
        # --- OrgsystemComponent: make category nullable and widen ---
        migrations.AlterField(
            model_name="orgsystemcomponent",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Copied from ComponentLibrary.category on creation",
                max_length=30,
                null=True,
            ),
        ),
    ]
