framework: hipaa-security-2013
source_framework: nist-csf-health-2024

mappings:
  - requirement: "PR.AC"
    entries:
      - "164.312(a)"
    sufficiency: full

  - requirement: "DE.CM"
    entries:
      - "164.312(b)"
    sufficiency: partial

  - requirement: "PR.AC"
    entries:
      - "164.312(e)"
    sufficiency: partial
