# Generated by Django 5.1.15 on 2026-05-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
        ('threat_models', '0002_remove_modeling_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatModelLibraryPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_model_associations', to='packs.librarypack')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_associations', to='threat_models.threatmodel')),
            ],
            options={
                'unique_together': {('threat_model', 'library_pack')},
            },
        ),
    ]
