# Generated by Django 5.1.15 on 2026-04-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardRequirementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sufficiency', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], default='partial', max_length=10)),
                ('from_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_mappings', to='compliance.standardrequirement')),
                ('source_pack', models.ForeignKey(blank=True, help_text='Pack that created this mapping, used for cleanup on pack delete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_mappings', to='packs.librarypack')),
                ('to_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mappings', to='compliance.standardrequirement')),
            ],
            options={
                'unique_together': {('from_requirement', 'to_requirement')},
            },
        ),
    ]
