# Generated by Django 5.1.15 on 2026-05-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_initial'),
        ('threats', '0003_alter_componentinstancecountermeasure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstancethreat',
            name='impact_description',
            field=models.TextField(blank=True, default='', help_text='Narrative description of what the attacker achieves'),
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='threat_actor',
            field=models.ForeignKey(blank=True, help_text='DFD actor who can initiate this threat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats_as_actor', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='threat_actor_text',
            field=models.CharField(blank=True, default='', help_text="Free-text threat actor when not linked to a DFD component (e.g. 'state actor', 'hacktivist')", max_length=100),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='impact_description',
            field=models.TextField(blank=True, default='', help_text='Narrative description of what the attacker achieves'),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='threat_actor',
            field=models.ForeignKey(blank=True, help_text='DFD actor who can initiate this threat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_threats_as_actor', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='threat_actor_text',
            field=models.CharField(blank=True, default='', help_text="Free-text threat actor when not linked to a DFD component (e.g. 'state actor', 'hacktivist')", max_length=100),
        ),
    ]
