# Generated by Django 5.1.15

import django.db.models.deletion
from django.db import migrations, models


def seed_threat_sources(apps, schema_editor):
    """Seed 4 ThreatSource rows from NIST SP 800-30r1."""
    ThreatSource = apps.get_model("threats", "ThreatSource")
    seeds = [
        {
            "slug": "adversarial",
            "name": "Adversarial",
            "description": "Individuals, groups, organizations, or states that seek to exploit dependence on cyber resources.",
        },
        {
            "slug": "accidental",
            "name": "Accidental",
            "description": "Erroneous actions taken by individuals in the course of executing their everyday responsibilities.",
        },
        {
            "slug": "structural",
            "name": "Structural",
            "description": "Failures of equipment, environmental controls, or software due to aging, resource depletion, or other circumstances which exceed expected operating parameters.",
        },
        {
            "slug": "environmental",
            "name": "Environmental",
            "description": "Natural disasters and failures of critical infrastructure on which the organization depends but which are outside the control of the organization.",
        },
    ]
    for seed in seeds:
        ThreatSource.objects.get_or_create(slug=seed["slug"], defaults=seed)


def reverse_seed(apps, schema_editor):
    ThreatSource = apps.get_model("threats", "ThreatSource")
    ThreatSource.objects.filter(
        slug__in=["adversarial", "accidental", "structural", "environmental"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("threat_models", "0001_initial"),
        ("threats", "0004_componentinstancethreat_impact_description_and_more"),
    ]

    operations = [
        # --- Remove threat_actor FK from both instance threat models ---
        migrations.RemoveField(
            model_name="componentinstancethreat",
            name="threat_actor",
        ),
        migrations.RemoveField(
            model_name="dataflowinstancethreat",
            name="threat_actor",
        ),
        # Update threat_actor_text help text
        migrations.AlterField(
            model_name="componentinstancethreat",
            name="threat_actor_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text threat actor (e.g. 'state actor', 'hacktivist')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="dataflowinstancethreat",
            name="threat_actor_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text threat actor (e.g. 'state actor', 'hacktivist')",
                max_length=100,
            ),
        ),
        # --- New models ---
        migrations.CreateModel(
            name="ThreatPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbolic_name",
                    models.SlugField(
                        help_text="Machine-readable identifier, e.g., 'malicious-insider'",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_person", models.BooleanField(default=True)),
                ("malicious_intent", models.BooleanField(default=True)),
                ("skill_level", models.CharField(blank=True, default="", max_length=100)),
                ("motivation", models.TextField(blank=True, default="")),
                ("resources", models.TextField(blank=True, default="")),
                ("objectives", models.TextField(blank=True, default="")),
                (
                    "format_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra fields from JSON for round-trip fidelity",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_personas",
                        to="threat_models.threatmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="threatpersona",
            constraint=models.UniqueConstraint(
                fields=("threat_model", "symbolic_name"),
                name="unique_persona_per_threat_model",
            ),
        ),
        migrations.CreateModel(
            name="ThreatPersonaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_links",
                        to="threats.threatpersona",
                    ),
                ),
                (
                    "component_threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_links",
                        to="threats.componentinstancethreat",
                    ),
                ),
                (
                    "flow_threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_links",
                        to="threats.dataflowinstancethreat",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="threatpersonalink",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("component_threat__isnull", False),
                    ("flow_threat__isnull", True),
                )
                | models.Q(
                    ("component_threat__isnull", True),
                    ("flow_threat__isnull", False),
                ),
                name="persona_link_exactly_one_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatpersonalink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("component_threat__isnull", False)),
                fields=("persona", "component_threat"),
                name="unique_persona_component_threat",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatpersonalink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flow_threat__isnull", False)),
                fields=("persona", "flow_threat"),
                name="unique_persona_flow_threat",
            ),
        ),
        migrations.CreateModel(
            name="ThreatSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ThreatSourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_links",
                        to="threats.threatsource",
                    ),
                ),
                (
                    "component_threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="threats.componentinstancethreat",
                    ),
                ),
                (
                    "flow_threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="threats.dataflowinstancethreat",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="threatsourcelink",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("component_threat__isnull", False),
                    ("flow_threat__isnull", True),
                )
                | models.Q(
                    ("component_threat__isnull", True),
                    ("flow_threat__isnull", False),
                ),
                name="source_link_exactly_one_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatsourcelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("component_threat__isnull", False)),
                fields=("source", "component_threat"),
                name="unique_source_component_threat",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatsourcelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flow_threat__isnull", False)),
                fields=("source", "flow_threat"),
                name="unique_source_flow_threat",
            ),
        ),
        # --- Seed ThreatSource rows ---
        migrations.RunPython(seed_threat_sources, reverse_seed),
    ]
